// Generated by https://quicktype.io

export interface TvResults {
    page:          number;
    results:       TvShow[];
    total_pages:   number;
    total_results: number;
}

export interface TvShow {
    adult:             boolean;
    backdrop_path:     string;
    id:                number;
    name:              string;
    original_language: OriginalLanguage;
    original_name:    string;
    overview:          string;
    poster_path:       string;
    media_type:        MediaType;
    genre_ids:         number[];
    popularity:        number;
    first_air_date:    string;
    vote_average:      number;
    vote_count:        number;
    origin_country:    string[];
}

export enum MediaType {
    Tv = "tv",
}

export enum OriginalLanguage {
    De = "de",
    En = "en",
    Ja = "ja",
    Ko = "ko",
}
